### ISSUE TITLE
Make 0.2 release preparations

### ISSUE THREAD

**Issue by a5kin** [a5kin/xentica#58]
Before 0.2 release, we have to make sure all necessary things are in places.
- [x] document all changes in ``CHANGELOG.md``
- [x] change version in ``setup.py``
- [x] make sure all tests are passing
- [x] write release notes in Xentica blog (draft)
- [x] make release at GitHub
- [x] publish package at PyPI
- [x] publish release notes

**Comment by robotateme** [comment]
Good! Tell me how you need to enter the architecture of Khachitryan.

пт, 3 мая 2019 г. в 14:43, Andrey Zamaraev <notifications@github.com>:

**Comment by a5kin** [comment]
Xentica 0.2.0 is finally released. You could check the release notes here:
http://artipixoids.a5kin.net/releases/2019/06/28/xentica-0.2.0-release.html

Any feedback is welcome, especially the benchmark results for your OS/GPU.

As planned, the work on the next version will begin somewhere this autumn, after Graviteka's single is released. Stay tuned for the future versions!
